### ISSUE TITLE
Restoring from a preset does not work

### ISSUE THREAD

**Issue by matteocoder** [waelk10/Metronome#8] opened 2016-12-16 23:07 UTC
To reproduce

1: save a set of bpm and beats
2: change those values to create a new set and start the metronome
3: restore from the set created in step 1 and try to start it

What will happen is that the metronome will still play the set created in step 2, ignoring the saved set and making it useless.

**Comment by waelk10** [comment] 2016-12-17 21:15
Couldn't reproduce the problem on my end, if you can send a video that'd
help, also, what's the running environment?

**Comment by matteocoder** [comment] 2016-12-18 12:41
I'm on an LG D331 non rooted running the LG rom based on Android 5.0.2
[Metronome_20161218073656.mp4.zip](https://github.com/waelk10/Metronome/files/659414/Metronome_20161218073656.mp4.zip)
here is the video, and thanks for the quick reply!

**Comment by waelk10** [comment] 2017-03-20 19:40
I know that this is too late, though I haven't had a lot of time lately.
Stumbled upon the issue again today, currently I'm not at home so I can't do much, I'll try to see what I can do over the weekend, though I can't promise a fix soon since I've been "out of the loop" for a while.
I'll try my best to push a fix this Saturday, though -as I said- I can't guarantee anything.

BTW: for anyone reading this, please try to reproduce the issue and tell me what happens (include your setup please), as I've managed to reproduce it on the latest version of the app on the March 2nd nightly of Lineage OS (i.e. Android Nougat) running on a OnePlusX (Onyx).

**Comment by matteocoder** [comment] 2017-03-21 14:48
Unfortunately I don't have the LG D331 anymore, but the issue is present in the latest version of the app on the Samsung GT-S7580 running AOSP 7.1.1

**Comment by waelk10** [comment] 2017-03-21 16:59
Well, if it is on AOSP and Lineage, then most likely if it gets fixed there it'll work everywhere else, as I said I'll try to squash the bug this weekend, hope it is a simple fix.

**Comment by waelk10** [comment] 2017-04-01 12:55
Sorry for being late again, but I got sidetracked by some exams, I've traced the issue back to the DB library, I will attempt to fix it today, but if it requires lots of refactoring of code, I'll have to delay that till the next week(end).

**Comment by waelk10** [comment] 2017-04-01 13:59
Seems like it would be easier to re-write the code to not use a DB (don't know what I was thinking at the time), I'll try to use the native interfaces or just read/write to a file.

**Comment by waelk10** [comment] 2017-04-01 18:10
Just a quick update:
I'm currently in the proccess of re-writing the preset system, moving to a file-based approach as it is much much simpler and more elegant, plus the fact that it is less likely to be affected by future changes to the API, but this'll take a while, I'll try to get it done in less than two weeks from now, but I can't promise anything seeing as I have lots of exams in this period...

**Comment by matteocoder** [comment] 2017-04-01 18:38
Take your time! Your academic life comes first!

**Comment by waelk10** [comment] 2017-04-14 13:06
Started a new branch with the fix, I'll try to pusht the changes today, if it all works I'll merge it with the master...

**Comment by waelk10** [comment] 2017-04-15 08:54
At this point most of the code is in place, just still very very buggy, I'll try to fix what I can today, but I don't expect it to be done today, as the changes are huge and bugs are to be expected, if I'm mostly satisfied with the results I'll push the changes to the new branch.
But it won't be in the master branch for a while I guess...

**Comment by waelk10** [comment] 2017-04-15 15:38
Squashed out a lot of bugs, but don't have the time today to clean everything up, I've pushed the changes to the new branch, hopefully in less than a week I'll get to stabilize that branch and merge it with the master branch.
If anyone can lend a hand, I'd greatly appreciate it!

**Comment by waelk10** [comment] 2017-04-17 19:52
More bug-squashing (check out the latest commit), still kinda unstable in two instances throughout the code, I know where the remaining bugs are (more or less).
It is just that I have to go back to uni tomorrow, so, basically till about Friday I won't have time to fix it, but hopefully by Saturday I'll merge the changes into the master branch...

**Comment by waelk10** [comment] 2017-04-21 10:09
Pushed the last of the changes to the new branch, will test the app locally for a while before merging into the master branch, if anyone can help with the testing I'd greatly appreciate that!

**Comment by waelk10** [comment] 2017-04-23 07:11
I'm not at home some, yeah...
But anyhow, since I haven't found any bugs I'll merge the changes into master and call it a day I guess...

**Closed** 2017-04-23 07:11 UTC
Labels: bug
